### ISSUE TITLE
Constantly losing connection to backend - Request Timed Out

### ISSUE THREAD

**Issue by bastiangeorg** [spotizerr-dev/spotizerr#330]
My frontend is constantly losing connection to the backend:
"Request Timed Out. The server did not respond in time. Please try again later."

I tried multiple browsers (Firefox, Edge and Chrome) on different computers (Windows 10 and 11) with exactly the same behavior.

I started with a lightly modified config in version 3.1.1, but also tried the unmodified example config now in version 3.3.0. All on Docker in a Debian VM running on Proxmox.

The developer console in my browser shows NS_BINDING_ABORTED on:
get system.svg
get history?limit=25&offset=0
get history?limit=25&offset=0
get list?page=1&limit=20
get config
get watch
get config
get watch

BUT if I try to load the settings page (which only works if I use the menu buttons and NOT a page refresh) I can then immediately load the history without any problem.

I can also use the search and download. Even if the connection to the backend breaks, the download is still going perfectly fine.

Any tips on how I could investigate this any further?

**Comment by Phlogi** [comment]
provide the app logs, is redis running?

**Comment by Phlogi** [comment]
@jpaffrath Does it work again when restarting the app? How exactly are you running it? docker-compose?
PS: The double logging issue was fixed in dev.

**Comment by jpaffrath** [comment]
I am running on docker-compose in its default configuration:

`name: spotizerr
services:
  spotizerr:
    image: cooldockerizer93/spotizerr:3.3.0
    user: "1000:1000" # Spotizerr user:group ids
    volumes:
    # Ensure these directories and the .cache file exist and are writable by the container user
    - ./data:/app/data # data directory, contains config, creds, watch, history
    - ./downloads:/app/downloads # downloads directory, contains downloaded files
    - ./logs:/app/logs # logs directory, contains logs
    - ./.cache:/app/.cache # cache file
    ports:
    # Port to expose the app on
    - 7171:7171
    container_name: spotizerr-app
    restart: unless-stopped
    env_file:
    # Ensure you have a .env file in the root of the project, with the correct values
    - .env
    depends_on:
    - redis
  redis:
    image: redis:alpine
    container_name: spotizerr-redis
    restart: unless-stopped
    env_file:
    - .env
    volumes:
    - redis-data:/data
    command: sh -c 'redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes'
volumes:
  redis-data:
    driver: local`

In fact, I havent done any configuration, everything is on its default values.
It does not work againg after restarting the app. Restarting the whole container does not help either. The error is not deterministic, sometimes it just works, sometimes the app gets the hiccups.
Do you need more information from me? Maybe it is related to my issue #333, maybe my hardware is not sufficient and it is loosing its connection because of this?

**Comment by bastiangeorg** [comment]
> provide the app logs, is redis running?

Okay, there was indeed a problem with redis I missed. Out of pure habit(?) I wasn't using "volumes: - redis-data:/data" but "volumes: - ./redis-data:/data" which resulted in a connection error.

When I change this back to match the provided compose.yaml everything seems to work fine and I can't find any errors in the log (there is only a warning left: Couldn't write token to cache at: .cache).

**Comment by bastiangeorg** [comment]
> Ensure your cache volume is correctly setup too for the remaining error.

Still not completely sure what happend exactly (because the file was modified right after the warning message) but I redid the access permissions and now there are no warnin messages left.

Thank you for pointing me in the right direction and for this really great project!

**Comment by bastiangeorg** [comment]
After a fine afternoon yesterday I'm unfortunately back to where all started: "Request Timed Out. The server did not respond in time. Please try again later.". Again with NS_BINDING_ABORTED on:
get history?limit=25&offset=0
get history?limit=25&offset=0
get list?page=1&limit=20
get config
get watch

Interestingly I get an OK in the logs:
spotizerr-app    | INFO:     10.0.10.30:59400 - "GET /api/auth/status HTTP/1.1" 200 OK
spotizerr-app    | INFO:     10.0.10.30:59410 - "GET /api/history?limit=25&offset=0 HTTP/1.1" 200 OK
spotizerr-app    | INFO:     10.0.10.30:59424 - "GET /api/history?limit=25&offset=0 HTTP/1.1" 200 OK
spotizerr-app    | INFO:     10.0.10.30:55100 - "GET /api/config HTTP/1.1" 200 OK
spotizerr-app    | INFO:     10.0.10.30:55112 - "GET /api/config/watch HTTP/1.1" 200 OK
spotizerr-app    | INFO:     10.0.10.30:59450 - "GET /sw.js HTTP/1.1" 200 OK
spotizerr-app    | INFO:     10.0.10.30:59462 - "GET /workbox-22361bcd.js HTTP/1.1" 200 OK

I also realised that I have 100% CPU load when completely in idle, just like @jpaffrath mentioned.

**Comment by bastiangeorg** [comment]
It has 2 CPUs (i5 @ 2.5 GHz) and 16 GiB of RAM. While downloading it has a CPU usage between 20-50 % and only uses about 2.5 GB of RAM. (The host is also just at 5-10 % CPU usage and 75 % RAM usage)

My compose.yaml:
```
name: spotizerr
services:
  spotizerr:
    image: cooldockerizer93/spotizerr:3.3.0
    user: 1000:1000 # Spotizerr user:group ids
    volumes:
      # Ensure these directories and the .cache file exist and are writable by the container user
      - ./data:/app/data # data directory, contains config, creds, watch, history
      - ./download:/app/downloads # downloads directory, contains downloaded files
      - ./logs:/app/logs # logs directory, contains logs
      - ./.cache:/app/.cache # cache file
    ports:
      # Port to expose the app on
      - 7171:7171
    container_name: spotizerr-app
    restart: unless-stopped
    env_file:
      # Ensure you have a .env file in the root of the project, with the correct values
      - .env
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: spotizerr-redis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - redis-data:/data
    command: sh -c 'redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes'
volumes:
  redis-data:
    driver: local
networks: {}
```

And I have the watchlist disabled.

**Comment by Phlogi** [comment]
I'm able to reproduce this. There is a PR upcoming to fix this. It has many performance improvements and should reduce the problems significantly. However it will need more testing too.

are you guys ready to run a development version? do you need instructions?

@spotizerr-dev would place PR most likely tomorrow. Optimises celery queue as well as the number for SSEs sent. FYA

**Comment by Phlogi** [comment]
> How much resources does your debian VM have available (vCPU, RAM, etc.)? Please share your docker-compose.yml file.
> 
> Do you have any playlists/artists on watchlist?

I was able to reproduce this with on a beefy server even, it's the code. =)

**Comment by Phlogi** [comment]
@bastiangeorg @jpaffrath you can use ghcr.io/phlogi/spotizerr:dev-pr-2 image which is a dev version with performance improvements.
